apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jztxzika8-python 
  janus-idp.io/tekton: jztxzika8-python
  backstage.io/kubernetes-id: jztxzika8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jztxzika8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  